spring:
  application:
    name: authservice
  datasource:
    url: jdbc:h2:mem:test_db
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
server:
  port: 8080